### ISSUE TITLE
filter vs forEach

### ISSUE THREAD

**Issue by gaboesquivel** [addyosmani/es6-equivalents-in-es5#30]
Is there a reason to prefer forEach over filter  ?

```
var fives = [];
var nums = [1, 2, 5, 15, 25, 32];
nums.forEach(v => {
  if (v % 5 === 0)
    fives.push(v);
});
```

over

```
var nums = [1, 2, 5, 15, 25, 32];
var fives = nums.filter(v => v % 5 === 0 )
```

**Comment by cliffordfajardo** [comment]
@gaboesquivel  - good eye here. Both examples are essentially doing the same thing, but the main differences I see with the two examples are:
- `forEach` is being used a side effect function (since it doesn't actually return anything), so we have to create an outer variable to store our results
-  `filter` does actually return something (the transformed array)  so we can just save the results of filter directly to the `fives` variable.

**Comment by dashed** [comment]
imo, `filter` is more appropriate b/c you generally want to avoid side-effects.

**Comment by addyosmani** [comment]
TBH it was an oversight. I wouldn't mind us switching over to `filter` for this particular example.

**Comment by gaboesquivel** [comment]
Just realized that's intended to be an difference between statement bodies. Filter is an expression since it returns a value, just as map in the example lines above.
